max_motor_values:
  index_base: 0
  index_spread: 10
  index_tip: 0
  middle_base: 0
  middle_spread: 100
  middle_tip: 0
  pinky_base: 0
  pinky_spread: 240
  pinky_tip: 0
  reserved_11: 255
  reserved_12: 255
  reserved_13: 255
  reserved_14: 255
  ring_base: 0
  ring_spread: 180
  ring_tip: 0
  thumb_base: 40
  thumb_tip: 135
  thumb_yaw: 19
max_values:
  index_base: 0.9660200560073742
  index_spread: 0.18356244743218972
  index_tip: 1.5393430129378278
  middle_base: 1.009815975927062
  middle_spread: 0.18356244743218972
  middle_tip: 1.378008030150713
  pinky_base: 0.8627685469258514
  pinky_spread: 0.5275458660795554
  pinky_tip: 1.4961566278442728
  reserved_11: 0.0
  reserved_12: 0.0
  reserved_13: 0.0
  reserved_14: 0.0
  ring_base: 1.0532778002662566
  ring_spread: 0.18356244743218972
  ring_tip: 1.3579344915056117
  thumb_base: 2.588498682766385
  thumb_tip: 2.9338314678138873
  thumb_yaw: 0.046547927188034285
min_motor_values:
  index_base: 255
  index_spread: 10
  index_tip: 255
  middle_base: 255
  middle_spread: 100
  middle_tip: 255
  pinky_base: 255
  pinky_spread: 240
  pinky_tip: 255
  reserved_11: 255
  reserved_12: 255
  reserved_13: 255
  reserved_14: 255
  ring_base: 255
  ring_spread: 180
  ring_tip: 255
  thumb_base: 255
  thumb_tip: 255
  thumb_yaw: 245
min_values:
  index_base: 0.06609696796523809
  index_spread: 0.18356244743218972
  index_tip: 3.141592653589793
  middle_base: 0.003497028555026217
  middle_spread: 0.18356244743218972
  middle_tip: 3.141592653589793
  pinky_base: 0.048222042979361425
  pinky_spread: 0.5275458660795554
  pinky_tip: 3.141592653589793
  reserved_11: 0.0
  reserved_12: 0.0
  reserved_13: 0.0
  reserved_14: 0.0
  ring_base: 0.02437476126438041
  ring_spread: 0.18356244743218972
  ring_tip: 3.141592653589793
  thumb_base: 2.912886982795279
  thumb_tip: 3.0167690977806427
  thumb_yaw: 0.03260324081954651
thumb_abd_calibration_points:
- angle: 2.103835359154958
  motor: 79
- angle: 1.846004112577093
  motor: 117
- angle: 1.5369170169863051
  motor: 150
- angle: 1.4438524224882783
  motor: 191
- angle: 0.4210354381975191
  motor: 255
