VERSION: 3.0.1 # 新增L6、O6、L10 RS485支持
LINKER_HAND:  # 手部配置信息
  LEFT_HAND:
    EXISTS: True # 是否存在左手
    TOUCH: True # 是否有压力传感器
    CAN: "can0"  # 配置CAN端口 默认can0 如果MODUBS不为"None",则CAN配置失效
    MODBUS: "None" # 通讯协议是否为485 默认None 如果启动485，则是设备端口 /dev/ttyUSB* CAN配置失效 当前只支持O6/L6.后续版本正在努力增加中
    JOINT: L20 # 左手型号 O6/L6/L7/L10/L20/G20/L21/L25/
    NAME: # 默认值，不用修改
      - joint41
      - joint42
      - joint43
      - joint44
      - joint45
      - joint46
      - joint47
      - joint48
      - joint49
      - joint50
      - joint51
      - joint52
      - joint53
      - joint54
      - joint55
      - joint56
      - joint57
      - joint58
      - joint59
      - joint60
    
  RIGHT_HAND:
    EXISTS: False # 是否存在右手
    TOUCH: False # 是否有压力传感器
    CAN: "can0"  # 配置CAN端口 默认can0 如果MODUBS不为"None",则CAN配置失效
    MODBUS: "None" # 通讯协议是否为485 默认None 如果启动485，则是设备端口 /dev/ttyUSB* CAN配置失效 当前只支持O6/L6.后续版本正在努力增加中
    JOINT: L6 # 右手型号 O6/L6/L7/L10/L20/G20/L21/L25/
    NAME:  # 默认值，不用修改
      - joint71
      - joint72
      - joint73
      - joint77
      - joint75
      - joint76
      - joint77
      - joint78
      - joint79
      - joint80
      - joint81
      - joint82
      - joint83
      - joint84
      - joint88
      - joint86
      - joint87
      - joint88
      - joint89
      - joint90
PASSWORD: "12345678" # 由于与can通讯，需要激活通讯接口用到系统管理员密码。只有Linux系统需要，windows系统不需要。RS485不需要修改，RS485需要给/dev/ttyUSB* 777权限
